# Generated by Django 5.1.2 on 2024-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmanagecryptocurrencies',
            name='last_notified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
