# Generated by Django 5.1 on 2024-09-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccountactivity',
            options={'managed': True},
        ),
    ]
