# Generated by Django 5.1 on 2024-09-30 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_activity', '0002_alter_adminaccountactivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccountactivity',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
