# Generated by Django 5.1 on 2024-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_currency', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_timestamp', models.DateTimeField()),
                ('transaction_status', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=20)),
                ('sender_mobile_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transaction_table',
            },
        ),
    ]
