FROM python:3.11-slim

WORKDIR /backend-notification

COPY requirements.txt /backend-notificationservice/
RUN pip3 install -r /backend-notificationservice/requirements.txt

COPY . .


CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]
