# Generated by Django 5.0.7 on 2024-08-07 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='notification',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='OTP Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='OTP', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
