# Generated by Django 5.0.7 on 2024-08-07 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0003_notification_created_at'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='notification',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
