# Generated by Django 5.1 on 2024-08-31 10:25

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffersNotifications',
            fields=[
                ('notification_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'special_offers_notifications',
            },
        ),
        migrations.DeleteModel(
            name='SpecialOffersNotification',
        ),
        migrations.AlterField(
            model_name='adminspecialoffers',
            name='content',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='specialoffersnotifications',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('user_id',), name='unique_user_notifications'),
        ),
    ]
