# Generated by Django 5.1 on 2024-09-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0002_specialoffersnotifications_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminspecialoffers',
            table='admin_special_offers',
        ),
    ]
